version: '3'
services:
  auto-bl3:
    build: .
    command: ["go", "run", "cmd/main.go", "-e", "${matt_jam3s@hotmail.com}", "-p", "${Sonthepit1!}"]
    volumes:
      - codes:/root/.config/bl3-auto-vip
volumes:
  codes:
